### ISSUE TITLE
bccomp() type error on certain MySQL column types

### ISSUE THREAD

**Issue by Endermanbugzjfc** [poggit/libasynql#45]
# Describe the bug
![image](https://user-images.githubusercontent.com/53002741/89806206-4db55580-db69-11ea-8b03-fed51a400408.png)
```
Fatal error: Uncaught TypeError: bccomp() expects parameter 1 to be string, int given in phar:///home/container/virions/libasynql.phar/src/poggit/libasynql/mysqli/MysqliThread.php:186
Stack trace:
#0 phar:///home/container/virions/libasynql.phar/src/poggit/libasynql/mysqli/MysqliThread.php(186): bccomp(1, '922337203685477...')
#1 phar:///home/container/virions/libasynql.phar/src/poggit/libasynql/mysqli/MysqliThread.php(224): poggit\libasynql\mysqli\MysqliThread->poggit\libasynql\mysqli\{closure}(1)
#2 phar:///home/container/virions/libasynql.phar/src/poggit/libasynql/mysqli/MysqliThread.php(155): poggit\libasynql\mysqli\MysqliThread->toSelectResult(Object(mysqli_result))
#3 phar:///home/container/virions/libasynql.phar/src/poggit/libasynql/base/SqlSlaveThread.php(85): poggit\libasynql\mysqli\MysqliThread->executeQuery(Object(mysqli), 3, 'SELECT record_i...', Array)
#4 [internal function]: poggit\libasynql\base\SqlSlaveThread->run()
#5 {main}
thrown in phar:///home/container/virions/libasynql.phar/src/poggit/libasynql/mysqli/MysqliThread.php on line 186
```

# Sample code
```
-- # 			{ pre_registered
-- # 			  :username string
SELECT record_id
FROM pre_registered
WHERE username = :username
LIMIT 1;
-- # 			}
```

# Expected behavior
`record_id` is a unsigned bigint, the error didn't occur when no result is selected

# Environment
OS: linux and idk other stuffs (Same result on Windows10)
PocketMine version: 3.14.2
Libasynql version: 3.3.1

**Comment by Endermanbugzjfc** [comment]
Somehow fixed by setting `record_id` to unsigned int

**Comment by SOF3** [comment]
This seems a bug indeed.

**Comment by matcracker** [comment]
Hi, I had the same problem today. ~Why is it necessary to manage precision? We shouldn't worry as we are using PHP 64-bit.~

Otherwise we need to use [CONVERT](https://dev.mysql.com/doc/refman/5.7/en/cast-functions.html#function_convert) function or use [GMP extension](https://www.php.net/manual/en/book.gmp.php) but I don't think it's included in PocketMine binaries files.

**Comment by matcracker** [comment]
However, there would be a problem, int casting is not possible. We must therefore transform the value into a float.

**Comment by SOF3** [comment]
unsigned longs?
